name: Publish GitHub release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        default: v*.*.*
      release_name:
        description: 'Special name changes'
        required: true
        default: Describe here what was changed
  pull_request:


jobs:
  create-release:
    runs-on: ubuntu-latest
    container:
      image: paritytech/ci-linux:1c0fde6a-20220811

    steps:
      - uses: actions/checkout@v2

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: v1.1.1
          message: Decrease governance periods

      - name: Build release
        run: cargo build --release

      - name: Rename artifacts
        run: mv ./target/release/governance2 ./target/release/governance2-v1.1.1

      - name: ➡️ Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: ./target/release/governance2-v1.1.1

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.1.1
          name: Decrease governance periods
          draft: false
          files: ./target/release/governance2-v1.1.1

